//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 装置監視システム.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsUpgrade {
            get {
                return ((bool)(this["IsUpgrade"]));
            }
            set {
                this["IsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color Panel1GreenBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1GreenBackColor"]));
            }
            set {
                this["Panel1GreenBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Panel1YellowBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1YellowBackColor"]));
            }
            set {
                this["Panel1YellowBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Panel1RedBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1RedBackColor"]));
            }
            set {
                this["Panel1RedBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Panel1EraseBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1EraseBackColor"]));
            }
            set {
                this["Panel1EraseBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color Panel1CutBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1CutBackColor"]));
            }
            set {
                this["Panel1CutBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Panel1DontBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1DontBackColor"]));
            }
            set {
                this["Panel1DontBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1GreenForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1GreenForeColor"]));
            }
            set {
                this["Panel1GreenForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1YellowForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1YellowForeColor"]));
            }
            set {
                this["Panel1YellowForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1RedForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1RedForeColor"]));
            }
            set {
                this["Panel1RedForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1EraseForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1EraseForeColor"]));
            }
            set {
                this["Panel1EraseForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1CutForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1CutForeColor"]));
            }
            set {
                this["Panel1CutForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel1DontForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1DontForeColor"]));
            }
            set {
                this["Panel1DontForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsGridSnap {
            get {
                return ((bool)(this["IsGridSnap"]));
            }
            set {
                this["IsGridSnap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LimeGreen")]
        public global::System.Drawing.Color Panel2GreenBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2GreenBackColor"]));
            }
            set {
                this["Panel2GreenBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Panel2YellowBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2YellowBackColor"]));
            }
            set {
                this["Panel2YellowBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Panel2RedBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2RedBackColor"]));
            }
            set {
                this["Panel2RedBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color Panel2EraseBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2EraseBackColor"]));
            }
            set {
                this["Panel2EraseBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color Panel2CutBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2CutBackColor"]));
            }
            set {
                this["Panel2CutBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Panel2DontBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2DontBackColor"]));
            }
            set {
                this["Panel2DontBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Panel1StopForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1StopForeColor"]));
            }
            set {
                this["Panel1StopForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Panel1StopBackColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel1StopBackColor"]));
            }
            set {
                this["Panel1StopBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("956")]
        public int Room2Width {
            get {
                return ((int)(this["Room2Width"]));
            }
            set {
                this["Room2Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int RegularlyTime {
            get {
                return ((int)(this["RegularlyTime"]));
            }
            set {
                this["RegularlyTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsListData {
            get {
                return ((bool)(this["IsListData"]));
            }
            set {
                this["IsListData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("エリア1")]
        public string Area1 {
            get {
                return ((string)(this["Area1"]));
            }
            set {
                this["Area1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("エリア2")]
        public string Area2 {
            get {
                return ((string)(this["Area2"]));
            }
            set {
                this["Area2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("緑点灯")]
        public string Panel1GreenName {
            get {
                return ((string)(this["Panel1GreenName"]));
            }
            set {
                this["Panel1GreenName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("黄点灯")]
        public string Panel1YellowName {
            get {
                return ((string)(this["Panel1YellowName"]));
            }
            set {
                this["Panel1YellowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("赤点灯")]
        public string Panel1RedName {
            get {
                return ((string)(this["Panel1RedName"]));
            }
            set {
                this["Panel1RedName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("消灯")]
        public string Panel1EraseName {
            get {
                return ((string)(this["Panel1EraseName"]));
            }
            set {
                this["Panel1EraseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("通信断")]
        public string Panel1CutName {
            get {
                return ((string)(this["Panel1CutName"]));
            }
            set {
                this["Panel1CutName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("データなし")]
        public string Panel1DontName {
            get {
                return ((string)(this["Panel1DontName"]));
            }
            set {
                this["Panel1DontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("監視しない")]
        public string Panel1StopName {
            get {
                return ((string)(this["Panel1StopName"]));
            }
            set {
                this["Panel1StopName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("緑点灯")]
        public string Panel2GreenName {
            get {
                return ((string)(this["Panel2GreenName"]));
            }
            set {
                this["Panel2GreenName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("黄点灯")]
        public string Panel2YellowName {
            get {
                return ((string)(this["Panel2YellowName"]));
            }
            set {
                this["Panel2YellowName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("赤点灯")]
        public string Panel2RedName {
            get {
                return ((string)(this["Panel2RedName"]));
            }
            set {
                this["Panel2RedName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("消灯")]
        public string Panel2EraseName {
            get {
                return ((string)(this["Panel2EraseName"]));
            }
            set {
                this["Panel2EraseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("通信断")]
        public string Panel2CutName {
            get {
                return ((string)(this["Panel2CutName"]));
            }
            set {
                this["Panel2CutName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("データなし")]
        public string Panel2DontName {
            get {
                return ((string)(this["Panel2DontName"]));
            }
            set {
                this["Panel2DontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2GreenForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2GreenForeColor"]));
            }
            set {
                this["Panel2GreenForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2YellowForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2YellowForeColor"]));
            }
            set {
                this["Panel2YellowForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2RedForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2RedForeColor"]));
            }
            set {
                this["Panel2RedForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2EraseForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2EraseForeColor"]));
            }
            set {
                this["Panel2EraseForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2CutForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2CutForeColor"]));
            }
            set {
                this["Panel2CutForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Panel2DontForeColor {
            get {
                return ((global::System.Drawing.Color)(this["Panel2DontForeColor"]));
            }
            set {
                this["Panel2DontForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsViewErrir {
            get {
                return ((bool)(this["IsViewErrir"]));
            }
            set {
                this["IsViewErrir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsViewOccupancy {
            get {
                return ((bool)(this["IsViewOccupancy"]));
            }
            set {
                this["IsViewOccupancy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsViewMaintenance {
            get {
                return ((bool)(this["IsViewMaintenance"]));
            }
            set {
                this["IsViewMaintenance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsViewMemo {
            get {
                return ((bool)(this["IsViewMemo"]));
            }
            set {
                this["IsViewMemo"] = value;
            }
        }
    }
}
